inherit_from: ./configs/TUM_RGB/tum.yaml
scene: freiburg1_desk
dataset: 'tumrgb_ext'
averaged_frames: 3
n_virtual_cams: 3
render_video: True
data:
  dataset_root: /cluster/scratch/fgirlanda/extended/
  gt_dataset_root: /cluster/scratch/fgirlanda/datasets/TUM_RGBD/rgbd_dataset_freiburg1_desk
  input_folder: rgbd_dataset_freiburg1_desk_blur_3
cam:
  H: 480 
  W: 640 
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  distortion: [0.2624, -0.9531, -0.0054, 0.0026, 1.1633]
