inherit_from: ./configs/ETH3D/eth3d.yaml


scene: table_3
dataset: 'eth3d_ext'
averaged_frames: 2
n_virtual_cams: 6
data:
  input_folder: table_3_blur_2
  gt_dataset_root: /cluster/scratch/fgirlanda/ETH3D/table_3
