inherit_from: configs/ReplicaBlurry/replica.yaml
scene: office3


meshing:
  gt_mesh_path: /cluster/scratch/fgirlanda/datasets/replica/cull_replica_mesh/office3.ply
data:
  input_folder: /cluster/scratch/fgirlanda/extended/office_3