inherit_from: configs/ReplicaBlurry/replica.yaml
scene: office1

tracking:
  frontend:
    keyframe_thresh: 4.00

meshing:
  gt_mesh_path: /cluster/scratch/fgirlanda/datasets/replica/cull_replica_mesh/office1.ply
data:
  input_folder: /cluster/scratch/fgirlanda/extended/office_1