inherit_from: configs/ReplicaBlurry/replica.yaml
scene: office4

tracking:
  frontend:
    keyframe_thresh: 2.75 

meshing:
  gt_mesh_path: /cluster/scratch/fgirlanda/datasets/replica/cull_replica_mesh/office4.ply
data:
  input_folder: /cluster/scratch/fgirlanda/extended/office_4